### PR TITLE
Fix Out Of Crates bug and You can't sell Special Cargo at this time

### PR DESCRIPTION
**Pull request by alessandromrc**
Apparently opening the terrorbyte screen and then closing it will solve the issue... seems fake but it's what it is.

### CODE REVIEW

**Comment by alessandromrc** [comment]
Now it also prevents "You can't sell Special Cargo at this time" meaning it is working flawlessly!

Ps. If we want to be 101% that we don't get out of crates we should just restart the freemode as it will 100% refresh the crate number.

**Comment by alessandromrc** [comment]
I've been testing this for around 1 hour and it made no issues... seems like this feature now is complete and fully working like expected.

**Comment by Sainan** [comment]
That is garbage for updating. The locals should be where the other locals are or have the `[[update]]` comment.

**Comment by alessandromrc** [comment]
@Sainan I've now added the update tags to each value.

**Comment by Sainan** [comment]
I just realised I already pointed this out well before the update, but you never reviewed my notes.

**Comment by alessandromrc** [comment]
I wonder where are those notes so I can look at them too :)

**Pull request closed without merging**
